---
###
### Tracing Collector Service
###
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: {{.Values.namespace}}
  labels:
    component: collector
    namespace: {{.Values.namespace}}
data:
  collector-config: |
    receivers:
      opencensus:
        port: 55678
      zipkin:
        port: 9411
      jaeger:
        jaeger-thrift-http-port: 14268
    queued-exporters:
      jaeger-all-in-one:
        num-workers: 4
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: {{printf "http://%s.%s:14268/api/traces" "jaeger" .Values.namespace }}
          timeout: 5s
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: {{.Values.namespace}}
  labels:
    component: collector
    namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  ports:
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: jaeger
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    component: collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/part-of: Linkerd
    component: collector
    namespace: {{.Values.namespace}}
  name: collector
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: collector
      namespace: {{.Values.namespace}}
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        component: collector
        namespace: {{.Values.namespace}}
    spec:
      containers:
      - command:
        - /occollector_linux
        - --config=/conf/collector-config.yaml
        env:
        - name: GOGC
          value: "80"
        image: {{.Values.collector.image.name}}:{{.Values.collector.image.version}}
        imagePullPolicy: {{.Values.collector.image.pullPolicy}}
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        name: oc-collector
        ports:
        - containerPort: 55678
        - containerPort: 9411
        - containerPort: 14268
        readinessProbe:
          httpGet:
            path: /
            port: 13133
        {{- if .Values.collector.resources -}}
        {{- include "partials.resources" .Values.collector.resources | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /conf
          name: collector-config-val
      serviceAccountName: collector
      volumes:
      - configMap:
          items:
          - key: collector-config
            path: collector-config.yaml
          name: collector-config
        name: collector-config-val
---
###
### Tracing Jaeger Service
###
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{.Values.namespace}}
  labels:
    component: jaeger
    namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    component: jaeger
  ports:
    - name: collection
      port: 14268
    - name: ui
      port: 16686
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: Linkerd
    component: jaeger
    namespace: {{.Values.namespace}}
  name: jaeger
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jaeger
      namespace: {{.Values.namespace}}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        component: jaeger
        namespace: {{.Values.namespace}}
    spec:
      containers:
      - args:
        - --query.base-path=/jaeger
        image: {{.Values.jaeger.image.name}}:{{.Values.jaeger.image.version}}
        imagePullPolicy: {{.Values.jaeger.image.pullPolicy}}
        name: jaeger
        ports:
        - containerPort: 14268
          name: collection
        - containerPort: 16686
          name: ui
        {{- if .Values.jaeger.resources -}}
        {{- include "partials.resources" .Values.jaeger.resources | nindent 8 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      serviceAccountName: jaeger
