controllerComponentLabel: linkerd.io/control-plane-component
controllerImage: gcr.io/linkerd-io/controller
controllerImageVersion: linkerdVersionValue
createdByAnnotation: linkerd.io/created-by
gateway: true
gatewayLocalProbePath: /health-local
gatewayLocalProbePort: 8888
gatewayName: linkerd-gateway
gatewayNginxImage: nginx
gatewayNginxImageVersion: 1.17
gatewayPort: 4180
gatewayProbePath: /health
gatewayProbePort: 4181
gatewayProbeSeconds: 3
identityTrustDomain: cluster.local
linkerdNamespace: linkerd
linkerdVersion: linkerdVersionValue
namespace: linkerd-multicluster
proxyOutboundPort: 4140
serviceMirror: true
logLevel: info
serviceMirrorRetryLimit: 3
serviceMirrorUID: 2103
remoteMirrorServiceAccount: true
remoteMirrorServiceAccountName: linkerd-service-mirror-remote-access-default
