version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "03:30"
      timezone: "UTC"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/web/app"
    schedule:
      interval: "daily"

