# Dependabot are scheduled to avoid contention with normal workday CI usage. We
# start running updates at 3AM UTC (7PM PST, 8AM IST) and stagger each
# subsequent update by 30m.
#
# JS updates are run weekly.
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "3:00"
      timezone: "UTC"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "3:30"
      timezone: "UTC"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "4:00"
      timezone: "UTC"

  - package-ecosystem: "npm"
    directory: "/web/app"
    schedule:
      # JS dependencies tend to be pretty noisy, so only check once per week.
      interval: "weekly"
      day: "sunday"
    ignore:
      # v6 is backwards-incompatible and requires lots of changes.
      # A compatibility layer should come out at some point
      # see https://reactrouter.com/docs/en/v6/upgrading/v5
      - dependency-name: "react-router-dom"
        update-types: ["version-update:semver-major"]
