required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name = "github.com/linkerd/linkerd2-proxy-api"
  version = "0.1.7"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "7b2c5ac9fc04fc5efafb60700713d4fa609b777b" # cobra has no release tags at time of writing

[[constraint]]
  name = "github.com/containernetworking/cni"
  revision = "v0.6.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.12.2"

[[constraint]]
  name = "github.com/briandowns/spinner"
  revision = "5cf08d0ac778f0d708570fe143e3f82fdb9f9007"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/pkg/browser"
  revision = "c90ca0c84f15f81c982e32665bffd8d7aac8f097" # browser has no release tags at time of writing

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "v0.17.2"

[[constraint]]
  name = "github.com/wercker/stern"
  revision = "b04b5491222d9743529cb859a20d34ce2bb763af" # pin to 1.6.0 until https://github.com/wercker/stern/issues/96 is resolved
