required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/lint/golint",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name = "github.com/linkerd/linkerd2-proxy-api"
  version = "v0.1.4"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "7b2c5ac9fc04fc5efafb60700713d4fa609b777b" # cobra has no release tags at time of writing

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/pkg/browser"
  revision = "c90ca0c84f15f81c982e32665bffd8d7aac8f097" # browser has no release tags at time of writing

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  revision = "9bb6ab929dcbe1c8393cd9ef70387cb69811bd1c"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "v0.17.2"
#
# k8s.io/client-go dependency fixes
# taken from https://github.com/kubernetes/client-go/blob/kubernetes-1.11.1/Godeps/Godeps.json
#

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"
