{{with .Values -}}
---
###
### Control Plane CA Trust
###
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-ca
  namespace: {{ .Namespace }}
  labels:
    {{ .ControllerComponentLabel }}: controller
  annotations:
    {{ .CreatedByAnnotation }}: {{ .CliVersion }}
type: Opaque
data:
  cert.pem: {{ b64enc .CATrust.CertPEM }}
  key.pem: {{ b64enc .CATrust.KeyPEM }}
{{end -}}
