{{with .Values -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: controller
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
    {{.SharedComponentLabel}}: "false"
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
data:
  {{- with .Configs.Global}}
  global: |
    {{.}}
  {{- end}}
  {{- with .Configs.Proxy}}
  proxy: |
    {{.}}
  {{- end }}
  {{- with .Configs.Install}}
  install: |
    {{.}}
  {{- end }}
{{- end}}
