{{with .Values -}}
---
###
### Service Profile Validator
###
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: linkerd-sp-validator-webhook-config
webhooks:
- name: linkerd-sp-validator.linkerd.io
  clientConfig:
    service:
      name: linkerd-sp-validator
      namespace: {{ .Namespace }}
      path: "/"
    caBundle: {{ b64enc .CATrust.RootPEM }}
  rules:
  - operations: [ "CREATE" , "UPDATE" ]
    apiGroups: ["linkerd.io"]
    apiVersions: ["v1alpha1"]
    resources: ["serviceprofiles"]
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-sp-validator
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: sp-validator
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.ControllerComponentLabel}}: sp-validator
  ports:
  - name: sp-validator
    port: 443
    targetPort: sp-validator
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: linkerd-sp-validator
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: sp-validator
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{.ControllerComponentLabel}}: sp-validator
  template:
    metadata:
      labels:
        {{.ControllerComponentLabel}}: sp-validator
      annotations:
        {{.CreatedByAnnotation}}: {{.CliVersion}}
    spec:
      serviceAccountName: linkerd-sp-validator
      containers:
      - name: sp-validator
        image: {{.ControllerImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        args:
        - "sp-validator"
        - "-controller-namespace={{.Namespace}}"
        - "-log-level={{.ControllerLogLevel}}"
        ports:
        - name: sp-validator
          containerPort: 8443
        volumeMounts:
        - name: caTrust
          mountPath: /var/run/linkerd/ca
          readOnly: true
        livenessProbe:
          httpGet:
            path: /ping
            port: 9997
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9997
          failureThreshold: 7
        {{ with .SPValidatorResources -}}
        {{- template "resources" . }}
        {{ end -}}
        securityContext:
          runAsUser: {{.ControllerUID}}
      volumes:
      - name: caTrust
        secret:
          secretName: linkerd-ca
{{end -}}
