{{with .Values -}}
---
###
### Web
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: web
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.ControllerComponentLabel}}: web
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: admin-http
    port: 9994
    targetPort: 9994
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: linkerd-web
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: web
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{.CliVersion}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{.ControllerComponentLabel}}: web
      annotations:
        {{.CreatedByAnnotation}}: {{.CliVersion}}
    spec:
      containers:
      - name: web
        ports:
        - name: http
          containerPort: 8084
        - name: admin-http
          containerPort: 9994
        volumeMounts:
        - name: config
          mountPath: /var/run/linkerd/config
        image: {{.WebImage}}
        imagePullPolicy: {{.ImagePullPolicy}}
        args:
        - "-api-addr=linkerd-controller-api.{{.Namespace}}.svc.cluster.local:8085"
        - "-grafana-addr=linkerd-grafana.{{.Namespace}}.svc.cluster.local:3000"
        - "-controller-namespace={{.Namespace}}"
        - "-log-level={{.ControllerLogLevel}}"
        livenessProbe:
          httpGet:
            path: /ping
            port: 9994
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9994
          failureThreshold: 7
        {{- include "resources" .WebResources | nindent 8 }}
        securityContext:
          runAsUser: {{.ControllerUID}}
      serviceAccountName: linkerd-web
      volumes:
      - name: config
        configMap:
          name: linkerd-config
{{end -}}
