---
###
### Web
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.Controller.ComponentLabel}}: web
  annotations:
    {{.Values.Internal.CreatedByAnnotation}}: {{.Values.CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.Controller.ComponentLabel}}: web
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: admin-http
    port: 9994
    targetPort: 9994
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.Controller.ComponentLabel}}: web
  annotations:
    {{.Values.Internal.CreatedByAnnotation}}: {{.Values.CliVersion}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        {{.Values.Controller.ComponentLabel}}: web
      annotations:
        {{.Values.Internal.CreatedByAnnotation}}: {{.Values.CliVersion}}
    spec:
      containers:
      - name: web
        ports:
        - name: http
          containerPort: 8084
        - name: admin-http
          containerPort: 9994
        image: {{.Values.Web.Image}}
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        args:
        - "-api-addr=linkerd-controller-api.{{.Values.Namespace}}.svc.cluster.local:8085"
        - "-grafana-addr=linkerd-grafana.{{.Values.Namespace}}.svc.cluster.local:3000"
        - "-uuid={{ uuidv4 }}"
        - "-controller-namespace={{.Values.Namespace}}"
        - "-log-level={{.Values.Controller.LogLevel}}"
        livenessProbe:
          httpGet:
            path: /ping
            port: 9994
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 9994
          failureThreshold: 7
        {{- if .Values.EnableHA }}
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
        {{- end }}
        securityContext:
          runAsUser: {{.Values.Controller.UID}}
      {{- include "containers.proxy" . | nindent 6 }}
        terminationMessagePolicy: FallbackToLogsOnError
      initContainers:
      {{- include "containers.init" . | nindent 6 }}
      serviceAccountName: linkerd-web
