apiVersion: v1
appVersion: edge-XX.X.X
description: A helm chart containing the resources to enable mirroring of services from a remote cluster
kubeVersion: ">=1.13.0-0"
icon: https://linkerd.io/images/logo-only-200h.png
name: "linkerd2-multicluster-link"
version: 0.1.0
