kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-service-mirror
  labels:
    ControllerComponentLabel: service-mirror
rules:
- apiGroups: [""]
  resources: ["endpoints", "services", "secrets", "namespaces"]
  verbs: ["list", "get", "watch", "create", "delete", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-service-mirror
  labels:
    ControllerComponentLabel: service-mirror
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-service-mirror
subjects:
- kind: ServiceAccount
  name: linkerd-service-mirror
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-service-mirror
  labels:
    ControllerComponentLabel: service-mirror
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ControllerComponentLabel: service-mirror
  name: linkerd-service-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      ControllerComponentLabel: service-mirror
  template:
    metadata:
      labels:
        ControllerComponentLabel: service-mirror
    spec:
      containers:
      - args:
        - service-mirror
        - -log-level={{.Values.logLevel}}
        - -event-requeue-limit={{.Values.eventRequeueLimit}}
        image: {{.Values.controllerImage}}:{{default .Values.linkerdVersion .Values.controllerImageVersion}}
        name: service-mirror
        securityContext:
          runAsUser: {{.Values.serviceMirrorUID}}
      serviceAccountName: linkerd-service-mirror
