{{with .Values -}}
---
###
### Controller
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-controller-api
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: controller
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" $.Chart.Version) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.ControllerComponentLabel}}: controller
  ports:
  - name: http
    port: 8085
    targetPort: 8085
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-destination
  namespace: {{.Namespace}}
  labels:
    {{.ControllerComponentLabel}}: controller
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" $.Chart.Version) .CliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.ControllerComponentLabel}}: controller
  ports:
  - name: grpc
    port: 8086
    targetPort: 8086
---
{{ if not .Proxy.Image.Version -}}
{{ $_ := set .Proxy.Image "Version" $.Chart.AppVersion -}}
{{ end -}}
{{ $_ := set .Proxy "WorkloadKind" "deployment" -}}
{{ $_ := set .Proxy "Component" "controller" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" $.Chart.Version) .CliVersion}}
  labels:
    {{.ControllerComponentLabel}}: controller
    {{.ControllerNamespaceLabel}}: {{.Namespace}}
  name: linkerd-controller
  namespace: {{.Namespace}}
spec:
  replicas: {{ternary .ControllerReplicas 1 (eq .HighAvailability true)}}
  selector:
    matchLabels:
      {{.ControllerComponentLabel}}: controller
      {{.ControllerNamespaceLabel}}: {{.Namespace}}
      {{- include "partials.proxy.labels" .Proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.CreatedByAnnotation}}: {{default (printf "linkerd/helm %s" $.Chart.Version) .CliVersion}}
        {{- include "partials.proxy.annotations" .Proxy| nindent 8}}
      labels:
        {{.ControllerComponentLabel}}: controller
        {{.ControllerNamespaceLabel}}: {{.Namespace}}
        {{- include "partials.proxy.labels" .Proxy | nindent 8}}
    spec:
      {{- if eq .HighAvailability true -}}
      {{- $local := dict "Component" "controller" "Label" .ControllerComponentLabel -}}
      {{- include "linkerd.pod-affinity" $local | nindent 6 -}}
      {{- end }}
      containers:
      - args:
        - "public-api"
        - "-prometheus-url=http://linkerd-prometheus.{{.Namespace}}.svc.cluster.local:9090"
        - "-tap-addr=linkerd-tap.{{.Namespace}}.svc.{{.ClusterDomain}}:8088"
        - "-controller-namespace={{.Namespace}}"
        - "-log-level={{.ControllerLogLevel}}"
        image: {{.ControllerImage}}:{{default $.Chart.AppVersion .ControllerImageVersion}}
        imagePullPolicy: {{.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9995
          initialDelaySeconds: 10
        name: public-api
        ports:
        - containerPort: 8085
          name: http
        - containerPort: 9995
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9995
        {{- if eq .HighAvailability true -}}
        {{- include "linkerd.resources" .PublicAPIResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
      - args:
        - "destination"
        - "-addr=:8086"
        - "-controller-namespace={{.Namespace}}"
        - "-enable-h2-upgrade={{.EnableH2Upgrade}}"
        - "-log-level={{.ControllerLogLevel}}"
        image: {{.ControllerImage}}:{{default $.Chart.AppVersion .ControllerImageVersion}}
        imagePullPolicy: {{.ImagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9996
          initialDelaySeconds: 10
        name: destination
        ports:
        - containerPort: 8086
          name: grpc
        - containerPort: 9996
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9996
        {{- if eq .HighAvailability true -}}
        {{- include "linkerd.resources" .DestinationResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.ControllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
      {{- include "partials.proxy" .Proxy | nindent 6 -}}
      initContainers:
      {{- include "partials.proxy-init" .ProxyInit | nindent 6 -}}
      serviceAccountName: linkerd-controller
      volumes:
      - name: config
        configMap:
          name: linkerd-config
      {{- include "partials.proxy-identity-volume" . | nindent 6 -}}
{{end -}}
