---
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccountNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.serviceAccountNamespace}}
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - get
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.serviceAccountNamespace}}
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.serviceAccountNamespace}}
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Values.serviceAccountName}}
subjects:
- kind: ServiceAccount
  name: {{.Values.serviceAccountName}}
  namespace: {{.Values.serviceAccountNamespace}}

