{{if .Values.enablePSP -}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-multicluster-link-psp-{{.Values.targetClusterName}}
  namespace: {{.Values.namespace}}
  labels:
    linkerd.io/extension: multicluster
    namespace: {{.Values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp
subjects:
- kind: ServiceAccount
  name: linkerd-service-mirror-{{.Values.targetClusterName}}
  namespace: {{.Values.namespace}}
{{ end -}}
