blank_issues_enabled: false
contact_links:
- name: ğŸ™‹ğŸ¾ Question
  url: https://github.com/linkerd/linkerd2/discussions/new
  about: If you need help debugging something or have a general question about Linkerd
