---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viz-psp
  namespace: {{.Values.namespace}}
  labels:
    linkerd.io/extension: viz
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tap
  namespace: {{.Values.namespace}}
- kind: ServiceAccount
  name: web
  namespace: {{.Values.namespace}}
{{ if .Values.grafana.enabled -}}
- kind: ServiceAccount
  name: grafana
  namespace: {{.Values.namespace}}
{{ end -}}
{{ if .Values.prometheus.enabled -}}
- kind: ServiceAccount
  name: prometheus
  namespace: {{.Values.namespace}}
{{ end -}}
