---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  {{ include "partials.namespace" . }}
  name: gateway-proxy-admin
  labels:
    linkerd.io/extension: multicluster
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  podSelector:
    matchLabels:
      app: {{.Values.gateway.name}}
  port: linkerd-admin
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  {{ include "partials.namespace" . }}
  name: proxy-admin
  labels:
    linkerd.io/extension: multicluster
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  server:
    name: gateway-proxy-admin
  client:
    # for kubelet probes
    unauthenticated: true
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-proxy-admin
  labels:
    linkerd.io/extension: multicluster
spec:
  podSelector:
    matchLabels:
      linkerd.io/control-plane-component: linkerd-service-mirror
  port: linkerd-admin
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  {{ include "partials.namespace" . }}
  name: service-mirror-proxy-admin
  labels:
    linkerd.io/extension: multicluster
spec:
  server:
    name: service-mirror-proxy-admin
  client:
    # for kubelet probes
    unauthenticated: true
