---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp
  namespace: {{.Values.namespace}}
  labels:
    linkerd.io/extension: multicluster
rules:
- apiGroups: ['policy', 'extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - linkerd-{{.Values.linkerdNamespace}}-control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multicluster-psp
  namespace: {{.Values.namespace}}
  labels:
    linkerd.io/extension: multicluster
    namespace: {{.Values.namespace}}
roleRef:
  kind: Role
  name: psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{.Values.gateway.name}}
  namespace: {{.Values.namespace}}
