---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: {{ .Release.Namespace }}
  name: service-mirror
  labels:
    component: linkerd-service-mirror
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
spec:
  podSelector:
    matchLabels:
      component: linkerd-service-mirror
  port: admin-http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: {{ .Release.Namespace }}
  name: service-mirror
  labels:
    component: linkerd-service-mirror
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
spec:
  server:
    name: service-mirror
  client:
    # In order to use `linkerd mc gateways` you need viz' Prometheus instance
    # to be able to reach the service-mirror. In order to also have a separate
    # Prometheus scrape the service-mirror an additional ServerAuthorization
    # resource should be created.
    meshTLS:
      serviceAccounts:
      - name: prometheus
        namespace: linkerd-viz
