---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: {{ .Release.Namespace }}
  name: jaeger-injector-webhook
  labels:
    linkerd.io/extension: jaeger
    component: jaeger-injector
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  podSelector:
    matchLabels:
      linkerd.io/extension: jaeger
      component: jaeger-injector
  port: jaeger-injector
  proxyProtocol: TLS
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: {{ .Release.Namespace }}
  name: jaeger-injector-admin
  labels:
    linkerd.io/extension: jaeger
    component: jaeger-injector
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  podSelector:
    matchLabels:
      linkerd.io/extension: jaeger
      component: jaeger-injector
  port: admin-http
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: {{ .Release.Namespace }}
  name: jaeger-injector
  labels:
    linkerd.io/extension: jaeger
    component: jaeger-injector
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  server:
    selector:
      matchLabels:
        linkerd.io/extension: jaeger
        component: jaeger-injector
  client:
    # traffic coming from the kubelet and from kube-api
    unauthenticated: true
