---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: controller
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  global: |
  {{- if .Values.configs -}}
  {{- if .Values.configs.global -}}
  {{.Values.configs.global | nindent 4}}
  {{- end }}
  {{- else -}}
  {{- include "linkerd.configs.global" . | nindent 4}}
  {{- end }}
  proxy: |
  {{- if .Values.configs -}}
  {{- if .Values.configs.proxy -}}
  {{.Values.configs.proxy | nindent 4}}
  {{- end }}
  {{- else -}}
  {{- include "linkerd.configs.proxy" . | nindent 4}}
  {{- end }}
  install: |
  {{- if .Values.configs -}}
  {{- if .Values.configs.install -}}
  {{.Values.configs.install | nindent 4}}
  {{- end }}
  {{- else -}}
  {{- include "linkerd.configs.install" . | nindent 4}}
  {{- end }}
  values: |
  {{- $values := deepCopy .Values }}
  {{- /*
    WARNING! All sensitive or private data such as TLS keys must be removed
    here to avoid it being publicly readable.
  */ -}}
  {{- $_ := unset $values.identity.issuer.tls "keyPEM"}}
  {{- $_ := unset $values.profileValidator "keyPEM"}}
  {{- $_ := unset $values.proxyInjector "keyPEM"}}
  {{- $_ := unset $values.tap "keyPEM"}}
  {{- $_ := unset $values "partials"}}
  {{- $_ := unset $values "configs"}}
  {{- toYaml $values | trim | nindent 4 }}
