---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-config
  namespace: {{.Values.global.namespace}}
  labels:
    {{.Values.global.controllerComponentLabel}}: controller
    {{.Values.global.controllerNamespaceLabel}}: {{.Values.global.namespace}}
  annotations:
    {{.Values.global.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.global.linkerdVersion) .Values.global.cliVersion}}
data:
  values: |
  {{- $values := deepCopy .Values }}
  {{- /*
    WARNING! All sensitive or private data such as TLS keys must be removed
    here to avoid it being publicly readable.
  */ -}}
  {{- if kindIs "map" $values.identity.issuer.tls -}}
    {{- $_ := unset $values.identity.issuer.tls "keyPEM"}}
  {{- end -}}
  {{- if kindIs "map" $values.profileValidator -}}
    {{- $_ := unset $values.profileValidator "keyPEM"}}
  {{- end -}}
  {{- if kindIs "map" $values.proxyInjector -}}
    {{- $_ := unset $values.proxyInjector "keyPEM"}}
  {{- end -}}
  {{- if kindIs "map" $values.tap -}}
    {{- $_ := unset $values.tap "keyPEM"}}
  {{- end -}}
  {{- $_ := unset $values "partials"}}
  {{- $_ := unset $values "configs"}}
  {{- $_ := unset $values "stage"}}
  {{- toYaml $values | trim | nindent 4 }}
