{{ if not .Values.disableHeartBeat -}}
---
###
### Heartbeat
###
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: linkerd-heartbeat
  namespace: {{.Values.namespace}}
  labels:
    app.kubernetes.io/name: heartbeat
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: {{default .Values.linkerdVersion .Values.controllerImageVersion}}
    {{.Values.controllerComponentLabel}}: heartbeat
    {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
spec:
  schedule: "{{.Values.heartbeatSchedule}}"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{.Values.controllerComponentLabel}}: heartbeat
            {{.Values.workloadNamespaceLabel}}: {{.Values.namespace}}
            {{- with .Values.podLabels }}{{ toYaml . | trim | nindent 12 }}{{- end }}
          annotations:
            {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
            {{- with .Values.podAnnotations }}{{ toYaml . | trim | nindent 12 }}{{- end }}
        spec:
          {{- if .Values.tolerations -}}
          {{- include "linkerd.tolerations" . | nindent 10 }}
          {{- end -}}
          {{- include "linkerd.node-selector" . | nindent 10 }}
          serviceAccountName: linkerd-heartbeat
          restartPolicy: Never
          containers:
          - name: heartbeat
            image: {{.Values.controllerImage}}:{{default .Values.linkerdVersion .Values.controllerImageVersion}}
            imagePullPolicy: {{.Values.imagePullPolicy}}
            args:
            - "heartbeat"
            - "-controller-namespace={{.Values.namespace}}"
            - "-log-level={{.Values.controllerLogLevel}}"
            {{- if .Values.prometheusUrl }}
            - "-prometheus-url={{.Values.prometheusUrl}}"
            {{- else }}
            - "-prometheus-url=http://linkerd-prometheus.{{.Values.namespace}}.svc.{{.Values.clusterDomain}}:9090"
            {{- end }}
            {{- if .Values.heartbeatResources -}}
            {{- include "partials.resources" .Values.heartbeatResources | nindent 12 }}
            {{- end }}
            securityContext:
              runAsUser: {{.Values.controllerUID}}
{{- end }}
