{{ if not .Values.disableHeartBeat -}}
---
###
### Heartbeat RBAC
###
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-heartbeat
  namespace: {{.Values.namespace}}
  labels:
    {{ include "partials.labels.controller-ns" . }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: ["linkerd-config"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-heartbeat
  namespace: {{.Values.namespace}}
  labels:
    {{ include "partials.labels.controller-ns" . }}
roleRef:
  kind: Role
  name: linkerd-heartbeat
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-heartbeat
  namespace: {{.Values.namespace}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-heartbeat
  namespace: {{.Values.namespace}}
  labels:
    {{ include "partials.labels.component" "heartbeat" }}
    {{ include "partials.labels.controller-ns" . }}
{{- include "partials.image-pull-secrets" .Values.imagePullSecrets }}
{{- end }}
