---
###
### Web RBAC
###
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
  resourceNames: ["linkerd-config"]
  {{- if not .Values.RestrictDashboardPrivileges }}
- apiGroups: [""]
  resources: ["namespaces", "configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts", "pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
roleRef:
  kind: Role
  name: linkerd-web
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.Values.Namespace}}
---
{{- if not .Values.RestrictDashboardPrivileges }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-{{.Values.Namespace}}-web-check
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  verbs: ["list"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["list"]
- apiGroups: ["linkerd.io"]
  resources: ["serviceprofiles"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-{{.Values.Namespace}}-web-check
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
roleRef:
  kind: ClusterRole
  name: linkerd-{{.Values.Namespace}}-web-check
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.Values.Namespace}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-{{.Values.Namespace}}-web-admin
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-{{.Values.Namespace}}-tap-admin
subjects:
- kind: ServiceAccount
  name: linkerd-web
  namespace: {{.Values.Namespace}}
---
{{- end}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Values.Namespace}}
  labels:
    {{.Values.ControllerComponentLabel}}: web
    {{.Values.ControllerNamespaceLabel}}: {{.Values.Namespace}}
