---
###
### Web
###
---
kind: Service
apiVersion: v1
metadata:
  name: linkerd-web
  namespace: {{.Values.namespace}}
  labels:
    {{.Values.controllerComponentLabel}}: web
    {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
spec:
  type: ClusterIP
  selector:
    {{.Values.controllerComponentLabel}}: web
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: admin-http
    port: 9994
    targetPort: 9994
---
{{ $_ := set .Values.proxy "workloadKind" "deployment" -}}
{{ $_ := set .Values.proxy "component" "linkerd-web" -}}
{{ include "linkerd.proxy.validation" .Values.proxy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
  labels:
    {{.Values.controllerComponentLabel}}: web
    {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
  name: linkerd-web
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.dashboard.replicas}}
  selector:
    matchLabels:
      {{.Values.controllerComponentLabel}}: web
      {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
      {{- include "partials.proxy.labels" .Values.proxy | nindent 6}}
  template:
    metadata:
      annotations:
        {{.Values.createdByAnnotation}}: {{default (printf "linkerd/helm %s" .Values.linkerdVersion) .Values.cliVersion}}
        {{- include "partials.proxy.annotations" .Values.proxy| nindent 8}}
      labels:
        {{.Values.controllerComponentLabel}}: web
        {{.Values.controllerNamespaceLabel}}: {{.Values.namespace}}
        {{- include "partials.proxy.labels" .Values.proxy | nindent 8}}
    spec:
      {{- include "linkerd.node-selector" . | nindent 6 }}
      containers:
      - args:
        - -api-addr=linkerd-controller-api.{{.Values.namespace}}.svc.{{.Values.clusterDomain}}:8085
        - -grafana-addr=linkerd-grafana.{{.Values.namespace}}.svc.{{.Values.clusterDomain}}:3000
        - -controller-namespace={{.Values.namespace}}
        - -log-level={{.Values.controllerLogLevel}}
        {{- $hostFull := replace "." "\\." (printf "linkerd-web.%s.svc.%s" .Values.namespace .Values.clusterDomain) }}
        {{- $hostAbbrev := replace "." "\\." (printf "linkerd-web.%s.svc" .Values.namespace) }}
        - -enforced-host=^(localhost|127\.0\.0\.1|{{ $hostFull }}|{{ $hostAbbrev }}|\[::1\])(:\d+)?$
        {{- include "partials.linkerd.trace" . | nindent 8 -}}
        image: {{.Values.webImage}}:{{default .Values.linkerdVersion .Values.controllerImageVersion}}
        imagePullPolicy: {{.Values.imagePullPolicy}}
        livenessProbe:
          httpGet:
            path: /ping
            port: 9994
          initialDelaySeconds: 10
        name: web
        ports:
        - containerPort: 8084
          name: http
        - containerPort: 9994
          name: admin-http
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9994
        {{- if .Values.webResources -}}
        {{- include "partials.resources" .Values.webResources | nindent 8 }}
        {{- end }}
        securityContext:
          runAsUser: {{.Values.controllerUID}}
        volumeMounts:
        - mountPath: /var/run/linkerd/config
          name: config
      - {{- include "partials.proxy" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ if not .Values.noInitContainer -}}
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      serviceAccountName: linkerd-web
      volumes:
      - configMap:
          name: linkerd-config
        name: config
      - {{- include "partials.proxy.volumes.identity" . | indent 8 | trimPrefix (repeat 7 " ") }}
