[package]
name = "linkerd-policy-controller-k8s-status"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
ahash = "0.8"
anyhow = "1"
# Fix for https://github.com/chronotope/chrono/issues/602
chrono = { version = "0.4.23", default-features = false, features = ["clock"] }
kubert = { version = "0.13", default-features = false, features = ["index"] }
linkerd-policy-controller-core = { path = "../../core" }
linkerd-policy-controller-k8s-api = { path = "../api" }
parking_lot = "0.12"
serde_json = "1.0.91"
thiserror = "1"
tokio = "1"
tracing = "0.1.37"
