[package]
name = "conduit-proxy-router"
version = "0.3.0"
authors = ["Carl Lerche <me@carllerche.com>"]
publish = false

[dependencies]
futures = "0.1"
indexmap = "1.0.0"
tower = { git = "https://github.com/tower-rs/tower" }
