dependencies:
- name: grafana
  version: 0.1.0
  repository: file://../add-ons/grafana
  condition: grafana.enabled
- name: partials
  version: 0.1.0
  repository: file://../partials
- name: tracing
  version: 0.1.0
  repository: file://../add-ons/tracing
  condition: tracing.enabled
