apiVersion: v1
appVersion: edge-XX.X.X
description: |
  A helm chart containing the resources to enable mirroring
  of services from a remote cluster.

  Warning: The purpose of this chart is just to support the `linkerd
  multicluster link` CLI command, which also produces the
  `cluster-credentials` secret and the Link CR, which are not found in this
  chart. Therefore this chart is not a replacement for that command, and
  shouldn't be used as-is unless you really know what you're doing ;-)
kubeVersion: ">=1.23.0-0"
icon: https://linkerd.io/images/logo-only-200h.png
name: "linkerd-multicluster-link"
version: 0.2.0
