Namespace: linkerd
CliVersion: linkerd/cli edge-19.2.5
EnableH2Upgrade: true
EnableHA: false
ImagePullPolicy: IfNotPresent
InboundAcceptKeepaliveMs: 10000
OutboundConnectKeepaliveMs: 10000
NoInitContainer: false
ProfileSuffixes: .
SingleNamespace: false
UUID: 1e0f82c4-0b28-42b9-ba3c-c7787b8b7d58

Ports:
  Outbound: 4140
  Inbound: 4143
  DestinationAPI: 8086
  IgnoreInbound: 4190,4191

Controller:
  ComponentLabel: linkerd.io/control-plane-component
  Image: gcr.io/linkerd-io/controller:edge-19.2.5
  LogLevel: info
  Replicas: 1
  HAReplicas: 2
  UID: 2103

Web:
  Image: gcr.io/linkerd-io/web:edge-19.2.5

Grafana:
  Image: gcr.io/linkerd-io/grafana:edge-19.2.5
  VolumeName: data

Prometheus:
  Image: prom/prometheus:v2.7.1
  VolumeName: data

TLS:
  Enabled: false
  CertFileName: certificate.crt
  IdentityVolumeSpecFileName: linkerd-secrets.yaml
  PrivateKeyFileName: private-key.p8
  SecretsVolumeName: linkerd-secrets
  TrustAnchorConfigMapName: linkerd-ca-bundle
  TrustAnchorFileName: trust-anchors.pem
  TrustAnchorVolumeName: linkerd-trust-anchors
  TrustAnchorVolumeSpecFileName: linkerd-trust-anchors.yaml

Proxy:
  AutoInjectEnabled: false
  ContainerName: linkerd-proxy
  ControlPort: 4190
  Image: gcr.io/linkerd-io/proxy:edge-19.2.5
  InitImage: gcr.io/linkerd-io/proxy-init:edge-19.2.5
  InitSpecFileName: proxy-init.yaml
  InjectAnnotation: linkerd.io/inject
  InjectDisabled: disabled
  LogLevel: warn,linkerd2_proxy=info
  MetricsPort: 4191
  SpecFileName: proxy.yaml
  UID: 2102

# These values are internal to the operation of linkerd,
# and should not be changed unless you are entirely sure of what you're doing.
Internal:
  Internal.CreatedByAnnotation: linkerd.io/created-by