on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      target:
        type: string
        required: false
        default: 'multi-arch'
    outputs:
      artifact-id:
        value: ${{ jobs.build.outputs.artifact-id }}

jobs:
  build:
    runs-on: ${{ vars.LINKERD2_RUNNER || 'ubuntu-24.04' }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        id: build
        with:
          build-args: |
            LINKERD_VERSION=${{ inputs.version }}
          target: ${{ inputs.target }}
          context: .
          file: cli/Dockerfile
          cache-from: type=gha,scope=${{ github.ref_name }}-cli
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-cli
          push: false
          load: false
          outputs: type=local,dest=.
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        id: upload
        with:
          name: cli-bin-${{ inputs.version }}-${{ inputs.target }}
          path: linkerd2-cli-${{ inputs.version }}-*
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
