name: Static checks
on:
  pull_request: {}
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - main
jobs:
  go_lint:
    name: Go lint
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13.4
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Go lint
      env:
        GITCOOKIE_SH: ${{ secrets.GITCOOKIE_SH }}
      run: |
        echo "$GITCOOKIE_SH" | bash
        bin/lint --verbose
  go_format:
    name: Go format
    runs-on: ubuntu-18.04
    container:
      image: golang:1.13.4
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Format
      env:
        GITCOOKIE_SH: ${{ secrets.GITCOOKIE_SH }}
      run: |
        echo "$GITCOOKIE_SH" | bash
        bin/fmt
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: shellcheck
      # For more information on shellcheck failures:
      # https://github.com/koalaman/shellcheck/wiki/Checks
      run: |
        bin/shellcheck-all
  #psscript-analyzer:
    #name: PSScriptAnalyzer
    #runs-on: ubuntu-18.04
    #steps:
    #- name: Checkout code
      # actions/checkout@v2
    #  uses: actions/checkout@722adc6
    #- name: Chocolatey - lint
      # devblackops/github-action-psscriptanalyzer@v2.0.0
    #  uses: devblackops/github-action-psscriptanalyzer@889a059
    #  env:
        # https://github.com/devblackops/github-action-psscriptanalyzer/pull/3/files
    #    INPUT_FAILONWARNING: 1
    #  with:
    #    rootPath: bin/win/tools
    #    failOnInfos: true
  markdown_lint:
    name: Markdown lint
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Markdown lint
      run: bin/markdownlint-all
