name: Static checks
on:
  pull_request:
    paths-ignore:
    - 'web/app/package.json'
  push:
    paths-ignore:
    - 'web/app/package.json'
    branches:
    - main
permissions: 
  contents: read
jobs:
  go_lint:
    name: Go lint
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container:
      image: golang:1.16.4
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Go lint
      run: bin/lint --verbose
  go_format:
    name: Go format
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container:
      image: golang:1.16.4
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Format
      run: bin/fmt
  proto_diff:
    name: Proto diff
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    container:
      image: golang:1.16.4
    steps:
      - name: Prerequisites
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install unzip
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Diff proto files
        run: bin/protoc-diff
  shellcheck:
    name: shellcheck
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: shellcheck
      # For more information on shellcheck failures:
      # https://github.com/koalaman/shellcheck/wiki/Checks
      run: |
        bin/shellcheck-all
  psscript-analyzer:
    name: PSScriptAnalyzer
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Chocolatey - lint
      uses: devblackops/github-action-psscriptanalyzer@819c15c7d02dec0611fe3ded6f8e259b0b925754
      env:
        # https://github.com/devblackops/github-action-psscriptanalyzer/pull/3/files
        INPUT_FAILONWARNING: 1
      with:
        rootPath: bin/win/tools
        failOnInfos: true
  markdown_lint:
    name: Markdown lint
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Markdown lint
      run: bin/markdownlint-all
  chart_docs_diff:
    name: Chart readme diff check
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Check docs for diff
      run: bin/helm-docs-diff
